### ISSUE TITLE
nodemon is causing the back end to crash on master

### ISSUE THREAD

**Issue by JordT** [JordT/blog-with-Node-React#20]
Error: listen EADDRINUSE: address already in use :::3005
[0]     at Server.setupListenHandle [as _listen2] (net.js:1331:16)
[0]     at listenInCluster (net.js:1379:12)
[0]     at Server.listen (net.js:1465:7)
[0]     at Function.listen (/Users/jordanthomson/code/blog-with-Node-React/node_modules/express/lib/application.js:618:24)
[0]     at Object.<anonymous> (/Users/jordanthomson/code/blog-with-Node-React/src/server/index.js:79:5)
[0]     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[0]     at Module.load (internal/modules/cjs/loader.js:950:32)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
[0]     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
[0] Emitted 'error' event on Server instance at:
[0]     at emitErrorNT (net.js:1358:8)
[0]     at processTicksAndRejections (internal/process/task_queues.js:82:21) {
[0]   code: 'EADDRINUSE',
[0]   errno: -48,
[0]   syscall: 'listen',
[0]   address: '::',
[0]   port: 3001
[0] }
[0] [nodemon] app crashed - waiting for file changes before starting...

**Comment by JordT** [comment]
Changing and saving a file e.g. app.js causes nodemon to restart and everything works. Looks like a port clash causing nodemon to fail

**Comment by JordT** [comment]
could have been a local issue - running 'pkill -f node' then 'nom start' seems to have resolved it.
